// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrFf5FJDS0FgEPzVlDB2nhpN8JgGRZx8',
    appId: '1:932504887346:web:c855f079be311780ab1c2b',
    messagingSenderId: '932504887346',
    projectId: 'm-music-796f8',
    authDomain: 'm-music-796f8.firebaseapp.com',
    storageBucket: 'm-music-796f8.appspot.com',
    measurementId: 'G-H9Z89TNDE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUOWuPdxWqNt-ATCgulHQJVqfkZT-oYQ',
    appId: '1:932504887346:android:895e6f768cf8158aab1c2b',
    messagingSenderId: '932504887346',
    projectId: 'm-music-796f8',
    storageBucket: 'm-music-796f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKyROQTI2vKV8SqxKTUe9jX6VgCp6jr0',
    appId: '1:932504887346:ios:1eaf07ae27c30d88ab1c2b',
    messagingSenderId: '932504887346',
    projectId: 'm-music-796f8',
    storageBucket: 'm-music-796f8.appspot.com',
    iosBundleId: 'com.example.mMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKyROQTI2vKV8SqxKTUe9jX6VgCp6jr0',
    appId: '1:932504887346:ios:1eaf07ae27c30d88ab1c2b',
    messagingSenderId: '932504887346',
    projectId: 'm-music-796f8',
    storageBucket: 'm-music-796f8.appspot.com',
    iosBundleId: 'com.example.mMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrFf5FJDS0FgEPzVlDB2nhpN8JgGRZx8',
    appId: '1:932504887346:web:15d4e36237dac35cab1c2b',
    messagingSenderId: '932504887346',
    projectId: 'm-music-796f8',
    authDomain: 'm-music-796f8.firebaseapp.com',
    storageBucket: 'm-music-796f8.appspot.com',
    measurementId: 'G-TSG17BMC3B',
  );
}
